services:
  dbs:
    image: mariadb:latest
    container_name: dbs
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=fluent
      - MYSQL_USER=local
      - MYSQL_PASSWORD=secret
    networks:
      - ssr-network2
    volumes:
      - ./data:/var/lib/mysql
      - ./dumps:/dumps

# ================= LARAVEL APPLICATION SERVICES ==========================

  php82:
    build:
      context: ./apps
      dockerfile: php82.Dockerfile
    restart: unless-stopped
    container_name: php82
    depends_on:
      - dbs
    volumes:
      - ./apps/fluent/src:/var/www/fluent.test
      - ./apps/express/src:/var/www/express.test
      - ./apps/act/src:/var/www/act.test
      - ./apps/fast/src:/var/www/fast.test
      - ./apps/rel/src:/var/www/rel.test
    networks:
      ssr-network2:
        aliases:
          - fluent.test
          - fluent-widget.test
          - act.test
          - act-engine.test
          - fluent-flask.test
          - express.test
          - fast.test
          - rel.test
      
# ==================== NGINX ===========================

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    depends_on:
      - php82
      - dbs
    ports:
      - "80:80"
      - "5173:5173"
      - "5174:5174"
      - "5175:5175"
      - "5176:5176"
      - "8001:8001"
    volumes:
      - ./apps/fluent/src:/var/www/fluent.test
      - ./apps/express/src:/var/www/express.test
      - ./apps/act/src:/var/www/act.test
      - ./apps/fast/src:/var/www/fast.test
      - ./apps/rel/src:/var/www/rel.test
      - ./apps/act-engine/src:/var/www/act-engine.test
      - ./apps/express-engine/src:/var/www/express-engine.test
    networks:
      ssr-network2:
        aliases:
          - fluent.test
          - fluent-widget.test
          - act.test
          - act-engine.test
          - fluent-flask.test
          - express.test
          - fast.test
          - rel.test


# ==================== PYTHON APPLICATIONS ==================

  fluent-flask:
    build:
      context: ./apps/fluent-flask
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: fluent-flask
    volumes:
      - ./apps/fluent-flask/src/app:/app
    environment:
      - MYSQL_HOST=dbs
      - MYSQL_PORT=3306
      - MYSQL_USER=local
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=fluent
      - ALLOWED_IPS=
      - APP_HOST_API=http://fluent.test/api/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      ssr-network2:
        aliases:
          - fluent.test
  
# ================== PHPMYADMIN ==========================

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    networks:
      - ssr-network2

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: soketi
    environment:
      SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: 'app-id'
      SOKETI_DEFAULT_APP_KEY: 'app-key'
      SOKETI_DEFAULT_APP_SECRET: 'app-secret'
    ports:
      - "6001:6001"
    networks:
      ssr-network2:
        aliases:
          - fluent.test
          - fluent-widget.test
          - ws.test

  fluent-widget:
    build:
      context: ./apps/fluent-widget
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: fluent-widget
    networks:
      ssr-network2:
        aliases:
          - fluent.test
          - fluent-widget.test
    volumes:
      - ./apps/fluent-widget/src:/var/www/fluent-widget.test

networks:
  ssr-network2:
    driver: bridge