services:
  db-fluent:
    image: mysql:8.3.0
    container_name: db-fluent
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=fluent
      - MYSQL_USER=local
      - MYSQL_PASSWORD=secret
    networks:
      - ssr-network2
    volumes:
      - ./data/fluent:/var/lib/mysql
      - ./dumps/fluent.sql.gz:/home/fluent.sql.gz

  db-express:
    image: mysql:8.3.0
    container_name: db-express
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=express
      - MYSQL_USER=local
      - MYSQL_PASSWORD=secret
    networks:
      - ssr-network2
    volumes:
      - ./data/express:/var/lib/mysql
      - ./dumps/express.sql.gz:/home/express.sql.gz

  db-act:
    image: mysql:8.3.0
    container_name: db-act
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=act
      - MYSQL_USER=local
      - MYSQL_PASSWORD=secret
    networks:
      - ssr-network2
    volumes:
      - ./data/act:/var/lib/mysql
      - ./dumps/act.sql.gz:/home/act.sql.gz



# ================= LARAVEL APPLICATION SERVICES ==========================
  
  php-fluent:
    build:
      context: ./apps/fluent
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php-fluent
    depends_on:
      - db-fluent
    networks:
      ssr-network2:
        aliases:
          - fluent.test
          - fluent-widget.test
          - ws.test
          - act.test
          - act-engine.test
          - fluent-flask.test
          - express.test
    volumes:
      - ./apps/fluent/src:/var/www/fluent.test

  php-express:
    build:
      context: ./apps/express
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php-express
    depends_on:
      - db-express
      - php-fluent
    networks:
      - ssr-network2
    volumes:
      - ./apps/express/src:/var/www/express.test

  php-act:
    build:
      context: ./apps/act
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php-act
    depends_on:
      - db-act
      - php-express
    networks:
      - ssr-network2
    volumes:
      - ./apps/act/src:/var/www/act.test


# ==================== NGINX ===========================

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    depends_on:
      - php-fluent
      - php-act
      - soketi
      - php-express
    ports:
      - "80:80"
      - "5173:5173"
      - "5174:5174"
      - "5176:5176"
      - "8001:8001"
      - "6001:6001"
    volumes:
      - ./apps/fluent/src:/var/www/fluent.test
      - ./apps/express/src:/var/www/express.test
      - ./apps/act/src:/var/www/act.test

    networks:
      ssr-network2:
        aliases:
          - fluent.test
          - fluent-widget.test
          - ws.test
          - act.test
          - act-engine.test
          - fluent-flask.test
          - express.test


# ==================== PYTHON APPLICATIONS ==================

  fluent-flask:
    build:
      context: ./apps/fluent-flask
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: fluent-flask
    volumes:
      - ./apps/fluent-flask/src/app:/app
    environment:
      - MYSQL_HOST=db-fluent
      - MYSQL_PORT=3306
      - MYSQL_USER=local
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=fluent
    networks:
      - ssr-network2
  
# ================== PHPMYADMIN ==========================

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    networks:
      - ssr-network2

networks:
  ssr-network2:
    driver: bridge