version: '3.8'

services:

  php-fpm:
    build: 
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php
    volumes:
      - ./fluent:/var/www/fluent.test
      - ./express:/var/www/express.test
      - ./act:/var/www/act.test
      - ./impress:/var/www/impress.test
      - ./fast:/var/www/fast.test
    networks:
      - some-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fluent-widget:
    build:
      context: ./nodejs20
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: fluent-widget
    volumes:
      - ./fluent-widget:/var/www/html
    networks:
      some-network:
        aliases:
          - fluent.test
          - fluent-widget.test

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./fluent:/var/www/fluent.test
      - ./express:/var/www/express.test
      - ./impress:/var/www/impress.test
      - ./fast:/var/www/fast.test
      - ./act:/var/www/act.test
      - ./engines/act/www:/var/www/act-engine.test
      - ./engines/eaat2/dist:/var/www/eaat2-engine.test
      - ./engines/express:/var/www/express-engine.test
    ports:
      - "80:80"
      - "5173:5173"
      - "5174:5174"
      - "5175:5175"
    networks:
      some-network:
        aliases:
          - fluent.test
          - express.test
          - fluent-widget.test
          - ws.test
          - impress.test
          - fast.test
          - act.test
          - act-engine.tes
          - impress.test
          - eaat2-engine.test
          - express-engine.test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - soketi
    # command: bash -c "cd /var/www/fluent.test && npm run dev"

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: soketi
    ports:
      - "6001:6001"
    environment:
      SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: 'app-id'
      SOKETI_DEFAULT_APP_KEY: 'app-key'
      SOKETI_DEFAULT_APP_SECRET: 'app-secret'
    networks:
      some-network:
        aliases:
          - fluent.test
          - fluent-widget.test
          - ws.test

networks:
  some-network:
   driver: bridge